### PR TITLE
handle hyphen for host number of viewers

### LINKED ISSUE #35: onHost can return NaN for number of viewers
## Bug Report

When connecting to a channel that is already hosting another channel, the `onHost` callback returns a value of `NaN` for the number of viewers rather than `undefined`.

This is due to a possible change in the notices that Twitch sends. Specifically, when connecting to a channel that is already hosting another channel, Twitch sends a notice in the form of `targetchannel -`, with a hyphen is in the viewer count position.

### Code

```
const twitchChat = await TwitchChatClient.forTwitchClient(twitchClient);
twitchChat.onHost((channel, target, viewers) => {
    console.log(`viewers ${isNaN(viewers) ? 'isNaN' : 'is a number'}`);
});
```

### Expected behavior

When connecting to a channel that is already hosting another channel, `onHost` should receive an `undefined` value for `viewers`.

### Actual Behavior

When connecting to a channel that is already hosting another channel, `onHost` receives `NaN` for `viewers`.

### Environment

n/a

### PR DESCRIPTION
**Pull request by lafiosca**
Fixes #35

### CODE REVIEW

File: packages/twitch-chat-client/src/ChatClient.ts [hunk 1]
```diff
@@ -501,7 +501,8 @@ export default class ChatClient extends IRCClient {
 				// unhost
 				this.emit(this.onUnhost, channel);
 			} else {
-				this.emit(this.onHost, channel, target, viewers ? Number(viewers) : undefined);
+				const numViewers = Number(viewers);
```
Comment (lafiosca) [inline packages/twitch-chat-client/src/ChatClient.ts]: In either the case that `viewers` is undefined or the case that `viewers` is a hyphen `-`, `numViewers` will be `NaN`.

**Comment by d-fischer** [comment]
Minor nitpick I fixed myself: Please try to avoid negated conditions in ternary expressions. (I added a lint rule for it too)

The fix was published in `twitch-chat-client@2.3.2`.
